
title: My Resume
url: 'http://webjeda.com'
baseurl: '/sean-park.github.com' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Junghyun Park
tagline: Software Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: junghyp4@uci.edu
website: blog.webjeda.com #do not add http://
linkedin: alandoe
github: sean-park
twitter: '@webjeda'

#Update all the sections by editing the files inside _includes folder.
