
title: Junghyun Park
url: 'http://webjeda.com'
baseurl: '/sean-park.github.com' #change it according to your repository name

#Profile information
name: Junghyun Park
tagline: Software Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: junghyp4@uci.edu
website: blog.webjeda.com #do not add http://
linkedin: junghyun-park-1306a9105
github: sean-park

#Update all the sections by editing the files inside _includes folder.
